Cypress.Commands.add('fillMandatoryFieldsAndSubmit', function(firstName, lastName, email, phone, product, text) {
  cy.get('#firstName').type(firstName)
  cy.get('#lastName').type(lastName)
  cy.get('#email').type(email)
  if(phone != '')
    cy.get('#phone').type(phone)
  if(product != '')
    cy.get('#product').select(product)
  cy.get('#open-text-area').type(text)
  cy.get('button[type="submit"]').click()
})
